name: build

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup just
        uses: ./
      - name: Check version
        run: just --version | grep -E '^just v?1\.57\.0$'
      - name: Test
        run: |
          [ "$(just --justfile tests/Justfile)" = "Test..." ]
